dist: trusty
language: cpp
addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - python3.6-dev
      - python3.6-venv
      - python3.7-dev
      - python3.7-venv
      - python3-pip
script:
  # c++ part, build and run c++ unit tests
  - python --version
  - python3 --version
  - python3.7 --version
  - which python
  - export CC=gcc-8
  - export CXX=g++-8
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j4
  - make test
  - cd ..
  # python part, run pytest with python3.7
  - python3.7 -m pip install --upgrade pip wheel setuptools pytest
  # - python3.7 setup.py build 
  # - python3.7 setup.py install
  # - python3.7 -m pytest
