
dist: trusty
language: cpp
addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - python3.6-dev
      - python3.7-dev
      - python3.7-venv

script:
  # c++ part, build and run c++ unit tests
  - python --version
  - python3 --version
  - python3.7 --version
  - pip --version
  - which python
  - which python3.7
  - which pip
  - export CC=gcc-8
  - export CXX=g++-8
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j4
  - make test
