
dist: trusty
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
script:
  # c++ part, build and run c++ unit tests
  - export CC=gcc-8
  - export CXX=g++-8
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j4
  - make test
  - cd ..

  # python part
  - which python