package:
  name: pytomlpp
  version: {{ '0.1.0' }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - pybind11
    - cmake

  run:
    - python
    - vs2015_runtime  # [win]

test:
  imports:
    - pytomlpp

about:
  summary: Python wrapper for tomlplusplus
  license_file: LICENSE
